### PR TITLE
Humble: Check if message has a "header" field with a stamp subfield of type builtin_interfaces::msg::Time (#51)

### PR DESCRIPTION
**Pull request by Timple**
As per request here: https://github.com/ros-tooling/libstatistics_collector/issues/152#issuecomment-1377670831

### CODE REVIEW

**Comment by christophebedard** [comment]
Thanks for the PR.

CI testing everything above `libstatistics_collector`:

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/17902/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/12470/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/18574/)

I think this is ABI compatible, as mentioned here https://github.com/ros-tooling/libstatistics_collector/pull/54#issuecomment-1258625423. @jacobperron @clalancette cc just in case.

**Review by MichaelOrlov — APPROVED** [review]
Backport looks good to me.
However don't know why so many failures on CI, especially in unrelated pep checks?
Re-runing CI for Linux at least.
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/17907/)

cc: @christophebedard

**Comment by christophebedard** [comment]
@MichaelOrlov looks like you have access to the release repository: https://github.com/ros2-gbp/ros2-gbp-github-org/blob/latest/tooling_wg.tf#L3. Would you mind doing a new release for Humble? You could possibly bump to 1.3.1.

**Comment by clalancette** [comment]
> @MichaelOrlov looks like you have access to the release repository: https://github.com/ros2-gbp/ros2-gbp-github-org/blob/latest/tooling_wg.tf#L3. Would you mind doing a new release for Humble? You could possibly bump to 1.3.1.

Let's hold off on this, as we are currently preparing a patch release: https://github.com/ros2/ros2/pull/1367

@audrow FYI

**Comment by christophebedard** [comment]
I think the patch release is done, so the release can be created now.

cc @MichaelOrlov

**Comment by Timple** [comment]
Subtle ping...

**Comment by MichaelOrlov** [comment]
@Timple Thanks for ping and sorry for the delay.  
Releasing already in progress https://github.com/ros/rosdistro/pull/36267

**Pull request merged**
