### PR TITLE
fix: add void annotation (#194)

### PR DESCRIPTION
**Pull request by wep21**
- backport #194 into jazzy

### CODE REVIEW

**Comment by christophebedard** [comment]
This looks good to me, but it looks like `jazzy` branches are frozen now, so this will have to wait a bit: https://discourse.ros.org/t/upcoming-freeze-for-jazzy-in-preparation-for-release/37828

**Comment by christophebedard** [comment]
Can you rebase on `jazzy`?

**Comment by wep21** [comment]
@christophebedard rebased!

**Review by christophebedard — APPROVED** [review]
Thanks!

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/21159/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/15463/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/21882/)

**Comment by wep21** [comment]
@christophebedard I appreciate it if you could create a new release for jazzy.

**Comment by christophebedard** [comment]
Done! It will be released into Jazzy as `1.7.3`: https://github.com/ros/rosdistro/pull/41783.

However, I do not know when it will be available in the main apt repo.

**Pull request merged**
