### PR TITLE
[Backport Foxy] Added benchmark test to libstatistics_collector (#57)

### PR DESCRIPTION
**Pull request by ahcorde**
* Added benchmark test to libstatistics_collector

Signed-off-by: ahcorde <ahcorde@gmail.com>

* cppcheck supressed unknown macro warning - macos

Signed-off-by: ahcorde <ahcorde@gmail.com>

* Reset heap counters

Signed-off-by: ahcorde <ahcorde@gmail.com>

* Added feedback

Signed-off-by: ahcorde <ahcorde@gmail.com>

* Remove unknownMacro suppression from CMakeLists.txt

Signed-off-by: ahcorde <ahcorde@gmail.com>

* Added feedback

Signed-off-by: ahcorde <ahcorde@gmail.com>

* moved benchmark test to test/benchmark

Signed-off-by: ahcorde <ahcorde@gmail.com>

* Added feedback

Signed-off-by: ahcorde <ahcorde@gmail.com>

Co-authored-by: Devin Bonnie <47613035+dabonnie@users.noreply.github.com>

### CODE REVIEW

**Comment by ahcorde** [comment]
Compiling up-to `libstatistics_collector` with `-DAMENT_RUN_PERFORMANCE_TESTS=ON`: and testing `libstatistics_collector`

* Linux [Build Status](http://ci.ros2.org/job/ci_linux/12650/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/7611/)
* macOS [Build Status](http://ci.ros2.org/job/ci_osx/10361/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/12581/)

**Comment by ahcorde** [comment]
The `osrf_testing_tools_cpp` memory tools aren't available for Windows or aarch64. Since the performance tests aren't enabled by default, merging this PR won't cause the CMake warning on regular builds. In practice, we have no plans to run these benchmarks on any platform other than Linux x86_64 anyway.

**Comment by ahcorde** [comment]
friendly ping @dabonnie, do you mind to have a look?

**Comment by dabonnie** [comment]
I'm not sure why `build_and_test_macOS (pull_request)` is failing here. Will re-rerun.

**Comment by dabonnie** [comment]
Not sure why CI is failing here, but it's currently passing on master via scheduled runs. Any thoughts @ahcorde?

**Comment by ahcorde** [comment]
It's failing on the copyright test because it's not able to find a python library. Maybe the macOS CI should be updated.

```
  [6.583s] 6: ModuleNotFoundError: No module named 'importlib_metadata'
```

**Comment by ahcorde** [comment]
I updated the Github actions and it looks better .Do you want a different PR for the Github Actions commit ? or can you "rebase and merge" ?

**Comment by dabonnie** [comment]
@ahcorde thanks for fixing the CI, happy to take those changes with this PR.

**Pull request merged**
