### PR TITLE
Add in missing cstdint include.

### LINKED ISSUE #164: Missing cstdint include
Fails to build on GCC 13.1.1 due to missing cstdint include in the following file

https://github.com/ros-tooling/libstatistics_collector/blob/ea410f582932718960a09f6419f88315cc71e1ab/include/libstatistics_collector/moving_average_statistics/types.hpp#LL43C5-L43C5

### PR DESCRIPTION
**Pull request by clalancette**
This should fix #164

### CODE REVIEW

**Comment by clalancette** [comment]
CI:
* Linux [Build Status](http://ci.ros2.org/job/ci_linux/18673/)
* Linux-aarch64 [Build Status](http://ci.ros2.org/job/ci_linux-aarch64/13200/)
* Windows [Build Status](http://ci.ros2.org/job/ci_windows/19401/)

**Review by christophebedard — APPROVED** [review]

**Comment by Yadunund** [comment]
Just checking, do we need to backport this to `iron`?

**Comment by clalancette** [comment]
> Just checking, do we need to backport this to `iron`?

I don't think it is necessary, since Iron doesn't target a gcc 13 compiler.  Also, we can always backport this later in a patch release.

But I don't feel strongly about it, so if you think we should, feel free.

**Comment by Yadunund** [comment]
Thanks for clarifying. Will skip for now.

**Comment by fujitatomoya** [comment]
@Mergifyio backport iron

**Comment by fujitatomoya** [comment]
I do not seem to have the write permission to this repository, either @clalancette or @christophebedard can you do me a favor? (see https://github.com/ros2/ros2/issues/1491#issuecomment-1753156132)

**Comment by clalancette** [comment]
@Mergifyio backport iron

**Comment by aboseley** [comment]
https://github.com/Mergifyio backport humble

**Comment by aboseley** [comment]
@clalancette , can you please backport this to humble

**Comment by fujitatomoya** [comment]
@Mergifyio backport humble

**Comment by fujitatomoya** [comment]
Ah i do not have permission here, friendly ping @clalancette @christophebedard

**Comment by MichaelOrlov** [comment]
https://github.com/Mergifyio backport humble

**Pull request merged**
